// <auto-generated />
using System;
using CCLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCLibrary.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230405110146_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CCLibrary.Products.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NetMassInGrams")
                        .HasColumnType("REAL");

                    b.Property<double>("NetMassInKilos")
                        .HasColumnType("REAL");

                    b.Property<double>("NetMassInPounds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CCLibrary.User.Profile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<double>("CaloriesGoal")
                        .HasColumnType("REAL");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HeightInCm")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsRemembered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretWordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("WeightInKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CCLibrary.Products.Consumable", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Product");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("REAL");

                    b.Property<double>("ServingSizeInGrams")
                        .HasColumnType("REAL");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Consumable");
                });

            modelBuilder.Entity("CCLibrary.Products.Dish", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Product");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Dish");
                });

            modelBuilder.Entity("CCLibrary.Products.Drink", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Consumable");

                    b.Property<bool>("IsCarbonated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Drink");
                });

            modelBuilder.Entity("CCLibrary.Products.Food", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Consumable");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Type")
                                .HasColumnName("Food_Type");
                        });

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("CCLibrary.Products.AlcoholDrink", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Drink");

                    b.Property<double>("AlcoholContent")
                        .HasColumnType("REAL");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("AlcoholDrink");
                });

            modelBuilder.Entity("CCLibrary.Products.EnergyDrink", b =>
                {
                    b.HasBaseType("CCLibrary.Products.Drink");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("EnergyDrink");
                });
#pragma warning restore 612, 618
        }
    }
}
